site_name: DEEP (Data Education and Exploration Project)
docs_dir: 'docs'
site_dir: 'site'
theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'blue'
  logo:
    icon: 'cloud'
  language: 'en'
repo_name: 'ricedatasci/deep'
repo_url: 'https://github.com/ricedatasci/deep'
edit_uri: 'edit/master/docs'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/ricedatasci'
nav:
  - Overview: index.md
  - Curriculum:
    - Git:
      - Overview: curriculum/git/overview.md
      - Exercise: curriculum/git/exercise.md
    - Python:
      - Installation: curriculum/python/installation.md
      - Overview: curriculum/python/overview.ipynb
      - Exercise: curriculum/python/exercise.ipynb
    - "Exploratory Data Analysis":
      - Overview: curriculum/eda/overview.md
      - Exercise: curriculum/eda/exercise.ipynb
    - Examples:
      - "US Senate Dataset": curriculum/examples/dataset.ipynb
      - "Party Breakdown over Time": curriculum/examples/party-breakdown.ipynb
      - "EDA Exercise": curriculum/examples/eda-exercise.ipynb
  - Contributors: contributors.md
  - Resources: resources.md
plugins:
  - mknotebooks:
      execute: true
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
